export const lsConf = {
    count_words: {
        name: 'count_words',
        def: 5,
    },
    success_offset: {
        name: 'success_offset',
        def: 0.05,
    },
    mistake_offset: {
        name: 'mistake_offset',
        def: 0.5,
    },
    // nativeLang: {
    //     name: 'native_lang',
    //     def: 'en-EN',
    // },
    // translationLang: {
    //     name: 'translation_lang',
    //     def: 'en-EN',
    // },
    learn_first: {
        name: 'learn_first',
        def: 15,
    },
    control_work_timer: {
        name: 'control_work_timer',
        def: 1,
    },
    speakRate: {
        name: 'speak_rate',
        def: 1,
    },
    translator: {
        name: 'translator',
        def: 'https://translate.google.com/?sl={{nativeLang}}&tl={{translationLang}}&text={{text}}&op=translate',
    },
    statsDays: {
        name: 'stats_days',
        def: 30,
    },
}

export const languagesConfig = new Map([
    ['ar-SA', 'Arabic'],
    ['bn-BD', 'Bangla'],
    ['bn-IN', 'Bangla'],
    ['cs-CZ', 'Czech'],
    ['da-DK', 'Danish'],
    ['de-AT', 'German'],
    ['de-CH', 'German'],
    ['de-DE', 'German'],
    ['el-GR', 'Greek'],
    ['en-AU', 'English'],
    ['en-CA', 'English'],
    ['en-GB', 'English'],
    ['en-IE', 'English'],
    ['en-IN', 'English'],
    ['en-NZ', 'English'],
    ['en-US', 'English'],
    ['en-ZA', 'English'],
    ['es-AR', 'Spanish'],
    ['es-CL', 'Spanish'],
    ['es-CO', 'Spanish'],
    ['es-ES', 'Spanish'],
    ['es-MX', 'Spanish'],
    ['es-US', 'Spanish'],
    ['fi-FI', 'Finnish'],
    ['fr-BE', 'French'],
    ['fr-CA', 'French'],
    ['fr-CH', 'French'],
    ['fr-FR', 'French'],
    ['he-IL', 'Hebrew'],
    ['hi-IN', 'Hindi'],
    ['hu-HU', 'Hungarian'],
    ['id-ID', 'Indonesian'],
    ['it-CH', 'Italian'],
    ['it-IT', 'Italian'],
    ['ja-JP', 'Japanese'],
    ['ko-KR', 'Korean'],
    ['nl-BE', 'Dutch'],
    ['nl-NL', 'Dutch'],
    ['no-NO', 'Norwegian'],
    ['pl-PL', 'Polish'],
    ['pt-BR', 'Portugese'],
    ['pt-PT', 'Portugese'],
    ['ro-RO', 'Romanian'],
    ['ru-RU', 'Russian'],
    ['sk-SK', 'Slovak'],
    ['sv-SE', 'Swedish'],
    ['ta-IN', 'Tamil'],
    ['ta-LK', 'Tamil'],
    ['th-TH', 'Thai'],
    ['tr-TR', 'Turkish'],
    ['zh-CN', 'Chinese'],
    ['zh-HK', 'Chinese'],
    ['zh-TW', 'Chinese'],
])
