name: NodeJS with Gulp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        yarn
        yarn build
        
    - name: Copy
      run: |
        mkdir git-page
        cp -r ./build/* ./git-page
      
    - name: Commit and push
      uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
      env:
        SSH_DEPLOY_KEY: ${{ secrets.WORKFLOW_DEPLOY_KEY }}
      with:
        source-directory: git-page/
        destination-github-username: 'FriJis'
        destination-repository-name: 'lang-learner-page'
        user-email: egorik580@gmail.com
        commit-message: pushed from lang-learner
        target-branch: master
                
